### PR TITLE
Fix lag and persist penalties

### PR DESCRIPTION
**Pull request by brian-brazil**
This is only a partial solution. To complete it the penalty logic should be implemented in the same way everything else is and all `update` calls in `game/*.java` removed, with the relevant penalty and penalty update logic moving to the `DefaultSkaterModel`.

This PR also persists penalties.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Fixes #57

**Review by frank-weinberg — COMMENTED** [review]
I'm not convinced your removal of the argument to sendUpdates is the correct fix.

If I understand the code correctly, there are three key sets:
1. The set of all keys, aka state.keySet()
2. The set of updated keys, aka the removed argument keys
3. The set of keys that the client has registered, aka Conn.paths

The original code checked 1 against 2, which is bad. The new code checks 1 against 3, which is better.
The correct solution would be to check 2 against 3.

Also this change has the potential to uncover previously hidden bugs in the clients: Unless there is another filter down the line, the old code sent all updates to all clients, while the new code only sends updates the client has registered. If a client forgets to register a path it needs, this would be hidden by the old code but result in missing updates with the new code.

**Comment by brian-brazil** [comment]
> The correct solution would be to check 2 against 3.

That may be better, but it requires a rewrite of how this entire data flow works as 2 doesn't exist currently. Keep in mind that `path` was a prefix, not an exact path. This is something that could be done in the future, but we have good confidence the current proposed code is good enough and it has been tested.

> If a client forgets to register a path it needs, this would be hidden by the old code but result in missing updates with the new code.

This is a possibility, however I didn't spot this in any of the code in the screens and none of the alpha testers reported issues.

**Comment by frank-weinberg** [comment]
2 does exist. It is in the removed argument `keys`. `WS.updateState()` (Sidenote: That method is also horribly inefficient.) makes sure that every element of `state` that is modified is added to that set before passing it to the connections. There should be no need to send subkeys of updated keys as they will be unchanged.

That being said, I am on board with getting this improvement shipped (assuming there are no severe issues with the later commits - I haven't reviewed them yet). We just should not consider the issue completely fixed yet and should have the possible uncovering of bugs in mind in case any reports come in.

**Comment by brian-brazil** [comment]
That change is just one part of the fix, the other is massively reducing the amount of data this code is handling in the first place. Between them it should be pretty hard for the performance to regress here.

**Review by frank-weinberg — COMMENTED** [review]
One more minor issue: Where the old code is indented with 1 tab per level, newly added code is indented with 2 spaces per level.

In terms of content everything should be good.

**Comment by frank-weinberg** [comment]
And I agree that reducing the size of updates removes the impact in terms of efficiency. But having analyzed the code, I now have a strong urge to make it  a. more efficient and b. easier to follow. I'll probably put in some effort to that end after the release is out.

**Comment by brian-brazil** [comment]
The existing code style is quite hard to work with, given the breadth of the changes I gave up trying to match it. I'm planning on running a formatter over it at some point, the number of brace-less if/for statements is a risk.

**Comment by jaredquinn** [comment]
@brian-brazil  yeah some of the core code is 10+ years old.  There's a plan to tackle that but no time.

**Pull request merged**
