### PR TITLE
Rename README to README.markdown

### PR DESCRIPTION
**Pull request by rogerharkavy**
Since the content for this file is in markdown, the filename extension should reflect it.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Isn't it usually `.md` ?

**Comment by rogerharkavy** [comment]
I researched it and there really isn't an agreed-upon extension for markdown, but .markdown is one that many editors and file managers (and GitHub) will recognize. Plus, .md is sometimes used by another file format in Linux.

**Comment by brian-brazil** [comment]
I've personally never seen .markdown, it's always been .md on github and elsewhere.

**Comment by rogerharkavy** [comment]
You can use either one (see Wikipedia), but on Linux machines, .md can also be a machine description file. I chose .markdown because it was less ambiguous and would be recognized by editors and GitHub. If there's a consensus to use .md instead, I'm ok with changing it.

**Comment by rogerharkavy** [comment]
Accidentally closed this, sorry. Can it be reopened?

**Comment by jaredquinn** [comment]
I can't re-open because the repository it was pulled from has been closed.

**Comment by rogerharkavy** [comment]
@jaredquinn I think there was more than one pull request that renamed README to README.markdown

**Pull request closed without merging**
