### PR TITLE
Make Tab Bar Hidable

### PR DESCRIPTION
**Pull request by frank-weinberg**

### CODE REVIEW

**Comment by brian-brazil** [comment]
The initial state's not right.

**Comment by frank-weinberg** [comment]
Turns out that initializing operator settings was severly broken and we just didn't notice as all defaulted to false.

**Comment by brian-brazil** [comment]
That's still not right, plus every 3rd click flickers instead of applying.

**Comment by frank-weinberg** [comment]
should work now.

**Pull request merged**
