### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by miketheman**
Renaming the file will enable the Markdown preview in GitHub to display a more friendly page.

### CODE REVIEW

**Comment by rogerharkavy** [comment]
@miketheman I created a similar issue to this and ended up using the .markdown extension. Not sure what happened to the issue, no problem, using .md works.

I would like to edit your version of the README to match some material so that it mirrors changes to the the wiki pages. We are just copying and pasting content from the wiki into the README. Is that ok?

**Comment by domagalski** [comment]
I've also made a pull request (#40), which includes a commit that renames README to README.md.

**Comment by rogerharkavy** [comment]
@domagalski @miketheman Hm. What's the best way to handle this, then? Which README.md should I edit to get the latest and greatest content from the wiki in there?

**Comment by miketheman** [comment]
@rogerharkavy Uncertain - I think it would depend on how the maintainers wish to accept changes.
Ultimately, you should be able to use whatever source is currently there, and not depend on someone else's branch.
This PR could/should be merged irrespective of any content, since it performs a rename only.
Any content-change PRs before or after would likely be able to be merged with little hassle.

@domagalski good point - I didn't notice the rename in that PR. If the maintainers merge 40 before this one, then this can be closed.

**Comment by rogerharkavy** [comment]
@miketheman So maybe just create a new issue and make my own changes to the README?

@domagalski If I do the above, I will make sure your info about compiling the .jar gets in there.

**Comment by brian-brazil** [comment]
Could you resolve conflicts please?

**Comment by rogerharkavy** [comment]
@brian-brazil I'm not sure what happened with my previous edits so I edited README again, renamed it to README.MD and copied the content from the wiki into the file. Created a new pull request.

**Comment by frank-weinberg** [comment]
Closing this, as it is superseded by #76.

**Pull request closed without merging**
