### PR TITLE
Set default background for the scoreboard view to plain black.

### PR DESCRIPTION
**Pull request by frank-weinberg**

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by brian-brazil** [comment]
Can you rebase this please?

**Comment by frank-weinberg** [comment]
I won't be able to do that before tonight. And given the simplicity of the change it may be easier to just close this PR and create a new one with just the change from https://github.com/rollerderby/scoreboard/pull/68/commits/984ff9ad51cc246da46919fdd10ecd7ec5eae46f

**Comment by brian-brazil** [comment]
Tonight's fine, I don't think there'll be a release until after the weekend.

**Comment by frank-weinberg** [comment]
Ok, my attempt at rebasing apparently only made things worse. I'll stop those efforts and recreate a clean PR from scratch.

**Pull request closed without merging**
