### PR TITLE
Make it easier to understand&handle there being points on initial.

### PR DESCRIPTION
**Pull request by brian-brazil**
Viewing trip 2 now also includes the initial's score, and a button
to insert before trip 1. This is as it's not obvious that the NI column
is the initial trip button.

Screenshot_2020-02-16_09-29-47

### CODE REVIEW

**Comment by riffreff** [comment]
I think, that is a really good short-term solution for the current issue. It makes the "4+4-issue" way more comprehensible and resolvable for users. 
I would like to see this implemented soon. And then over the next months we will see, if users still can't learn to use the Trip +1 button. And then consider if it still needs a re-visit of the concept.

**Comment by AdamSmasherDerby** [comment]
I support this change, but only IN ADDITION to automatically assigning all points to a scoring trip.  That way, in the overtime and other ruleset cases where a user would want to assign points to the first trip, it is obvious how to do so.

However, I can not support this as an alternative to getting #439 implemented, because points on an initial trip are wrong.  We should not be making wrong data.

**Comment by brian-brazil** [comment]
> That way, in the overtime and other ruleset cases where a user would want to assign points to the first trip, it is obvious how to do so.

I don't think this is what you meant to say.

> And then over the next months we will see, if users still can't learn to use the Trip +1 button. And then consider if it still needs a re-visit of the concept.

I think a wait and see approach is a good idea, this is all pretty new still. Changing the behaviour also risks confusion this early on.

In the longer term if this ends up becoming rare we could remove/trim this to simplify things, and rely on the trip navigation (i.e. buttons for view prev/next trip) that'll be also be present by then. Plus the knowledge that'll have accumulated within the userbase.

**Comment by frank-weinberg** [comment]
We should definitely have an explanatory text and quick fix (resp. undo) button. Either standalone as suggested here or as a part of #439. 
But overall I still favor #439 and as to me it seems that that PR will be ready within the next week I dont think it's worth it to add this now just to replace it after a few days.

**Comment by brian-brazil** [comment]
> to me it seems that that PR will be ready within the next week 

That doesn't seem likely to me, even presuming that we agree it should be merged. It's already been a week and the more complex interactions have yet to be touched on.

**Comment by brian-brazil** [comment]
After some thought I've tweaked the wording to indicate what you could have done to not get into this situation. Keeping it succinct, correct, understandable and non-accusatory is surprisingly tricky.

**Comment by AdamSmasherDerby** [comment]
Nice job with the text - definitely agree that "concise" and "understandable" are mutually opposing goals here. Recommend merge.

**Comment by brian-brazil** [comment]
Yeah, the trick was finding a way not to have to mention overtime jams or non-lead jammers.

**Comment by frank-weinberg** [comment]
Superseded by #439

**Pull request closed without merging**
