### PR TITLE
Always show a jam score if there is one.

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by frank-weinberg** [comment]
But points during initial never happen. So what does this PR even fix? ;)

**Comment by brian-brazil** [comment]
Overtime jams :)

**Comment by JeneralPain** [comment]
Except that’s during a triggered OTJ not during normal jams

**Comment by brian-brazil** [comment]
Overtime jams aren't that special, and the scoreboard view doesn't even know that they happen.

**Pull request merged**
