### PR TITLE
Improve usability of the lineup tracker screen

### PR DESCRIPTION
**Pull request by frank-weinberg**
- Use roster numbers instead of skater names as main identifier
- Sort skaters by number by default
- Order positions as Jammer, Pivot, Blocker

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do you have a screenshot?

**Comment by frank-weinberg** [comment]
screenshot_20180822_001748

**Comment by frank-weinberg** [comment]
Current version for comparison:
screenshot_20180822_002010

**Comment by brian-brazil** [comment]
That's an improvement alright. Can we get rid of the ^v too?

**Comment by frank-weinberg** [comment]
I wouldn't remove them altogether as they serve to indicate that the table can be sorted by these columns. But it may be possible to replace them by proper arrow glyphs.

**Comment by brian-brazil** [comment]
Given it's now sorted by skater number, do we really need any other sorting options?

**Comment by frank-weinberg** [comment]
They are automatically included by using `sortedtable.js`. Reimplementing part of that in order to remove functionality sounds like a bad use of time.

**Comment by frank-weinberg** [comment]
Screenshot with modified headers:
screenshot_20180822_005129

**Comment by frank-weinberg** [comment]
The CircleCI fail is due to the clock sync issue, the fix for which is not included in this branch.

**Comment by brian-brazil** [comment]
I think longer term we should be looking at getting rid of them. They're UI clutter on a screen which needs to be used under time pressure, and a mis-press that could cause problems could easily happen.

**Comment by frank-weinberg** [comment]
The screen will need to be modified anyway, when we start tracking Box entries and exits for statsbook-generation. (We need to distinguish a cancelled misclick from an actual entry/exit pair, a way to handle substitutes and probaly other edge case handling.)

**Pull request merged**
