### PR TITLE
init roster view

### LINKED ISSUE #569: Announcer view
As an announcer for bouts, I would like a read-only view so that I can properly announce team rosters and also as a reference for in-game announcements.

### PR DESCRIPTION
**Pull request by atkinsonm**
Resolves #569 

Very basic initial "roster" view. Basically a copy of the team tab in the operator panel with inputs disabled and other buttons removed.

image

### CODE REVIEW

**Comment by atkinsonm** [comment]
Things I'd like to change if I get more time and sharpen my webdev skills:

* Remove the tab view
* Ensure it is mobile-friendly (I haven't actually tried it on mobile yet)
* Add team logos if present
* Change the inputs/selects to normal text and format as appropriate

But functionally speaking this is a good first version IMO.

**Comment by frank-weinberg** [comment]
At least removing the tab and turning inputs into text should be straightforward. Adding logos should also be relatively easy. I'll look into those later this week.

**Comment by frank-weinberg** [comment]
This is how it looks now:

Screenshot_20230215_221026

**Comment by atkinsonm** [comment]
Looks great! Thanks for taking it to the finish line

**Pull request merged**
