### PR TITLE
Fix button labels when a jam auto ends after 2 min

### PR DESCRIPTION
**Pull request by frank-weinberg**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do we have unittests for these?

**Comment by frank-weinberg** [comment]
No. Could probably add that to the existing tests.

**Comment by frank-weinberg** [comment]
Added unit tests (and can't reproduce the crash from CircleCI)

**Comment by brian-brazil** [comment]
We should probably figure out what that is, try adding `showoutput="yes"` to the junit task in build.xml.

**Comment by frank-weinberg** [comment]
That didn't really help. But it's a different testcase now.

**Comment by brian-brazil** [comment]
Looks like we're running out of RAM, possibly as we've two JVMs running given the forked unittests. Add maxmemory="128m" to the JVM line.

**Comment by frank-weinberg** [comment]
Should we leave the showoutput flag?

**Comment by brian-brazil** [comment]
Can't hurt.

**Comment by frank-weinberg** [comment]
done

**Pull request merged**
