### PR TITLE
 Whiteboard Team colors same as Penalty tracker

### PR DESCRIPTION
**Pull request by riffreff**
This would make the whiteboard headers coloured and pull those colours from the operator colours. 
Congruent to the PT screen

(first commit seems already merged, but still shows up here)

### CODE REVIEW

**Comment by frank-weinberg** [comment]
Whiteboard is public facing, using operator color is counterintuitive here.

We should discuss the handling of colors in general: The current setup of having n pairs of colors defined for m > n screens is bound to always cause difficulties. Let's either have a separate color for each screen or (better IMO) define one pair of colors and a set of binary options that define which screens use colors at all.

**Comment by brian-brazil** [comment]
Yeah, this whole area needs cleanup. At the least we'd want one operator and one public colourset.

**Comment by riffreff** [comment]
At the moment there is NO colour indication on the whiteboard. Making it the same as the Penalty Tracker is very intuitive. 

This was meant to be a quick resolution to user requests. Which could simply be implemented and a "bigger" solution could come later

**Comment by riffreff** [comment]
This was meant to be a quick resolution to user requests. Whcih could simply be omplemented and a "bigger" solution could come later

**Pull request merged**
