### PR TITLE
Caps lock

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by brian-brazil** [comment]
This updates state any time a key is pressed (including capslock). That's the most that seems possible with JS.

**Comment by frank-weinberg** [comment]
When pressing Caps Lock itself the display status is set the wrong way. On all other key presses (including Shift or Control) it works as expected.

**Comment by brian-brazil** [comment]
It's working correctly for me. What OS/Browser are you on?

**Comment by frank-weinberg** [comment]
This was with Firefox and IE on Win7. Can try with Firefox and Chrome under Linux later today.

**Comment by frank-weinberg** [comment]
On Linux it works as expected in both browsers. So it's a Windows problem. (And I won't be at my Windows computer for the next two weeks.)

**Comment by brian-brazil** [comment]
Okay, presumably Windows changes when the Caps Lock is activated at a different point in the key press than Linux.

**Comment by brian-brazil** [comment]
I've tweaked this so it should work better across OSes.

**Comment by frank-weinberg** [comment]
This appears to work correctly now on all combinations of Win7 or Linux with Firefox or Chrome.

**Pull request merged**
